import Head from "next/head";
import styled from "styled-components";
import Header from "./components/Header";
import Homes from "./components/Homes";

export default function Home() {
  return (
    <div>
      <Head>
        <title> Tesla Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header />
        <Homes />
      </main>
    </div>
  );
}
